TARDIS_SPAWNER_CONFIG = TARDIS_SPAWNER_CONFIG or {}
TARDIS_SPAWNER_CONFIG.Theme = TARDIS_SPAWNER_CONFIG.Theme or {}

TARDIS_SPAWNER_CONFIG.Theme.Body = Color(40, 45, 56)

TARDIS_SPAWNER_CONFIG.Theme.Primary = Color(45, 51, 63)

TARDIS_SPAWNER_CONFIG.Theme.Secondary = Color(31, 35, 43)

TARDIS_SPAWNER_CONFIG.Theme.Accent = Color(0, 195, 255)

TARDIS_SPAWNER_CONFIG.Theme.Accent2 = Color(0, 175, 228)

TARDIS_SPAWNER_CONFIG.Theme.Red = Color(224, 67, 67)

TARDIS_SPAWNER_CONFIG.Theme.Green = Color(90, 255, 68)

TARDIS_SPAWNER_CONFIG.Theme.Blue = Color(59, 126, 226)

TARDIS_SPAWNER_CONFIG.Theme.Text = Color(211, 211, 211)

TARDIS_SPAWNER_CONFIG.Theme.TextAccent = Color(255, 255, 255)

TARDIS_SPAWNER_CONFIG.Theme.Font = "Conthrax Sb"

TARDIS_SPAWNER_CONFIG.Theme.Roundness = 8